apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 2
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: danielhenrif/hello-go:v4
          envFrom:
            - configMapRef:
                name: goserver-env
          # - name: NAME
          #   #value: "Daniel"
          #   valueFrom: 
          #     configMapKeyRef: 
          #       name: goserver-env
          #       key: NAME  
          # - name: AGE
          #   #value: "23"
          #   valueFrom: 
          #     configMapKeyRef: 
          #       name: goserver-env
          #       key: AGE

# kubectl apply -f k8s/deployment.yaml
