# Aula 94
apiVersion: v1 
kind: Service
metadata:
  name: goserver-service
spec:
  selector: #Filtra todos os pods incorporados no serviço
    app: goserver #Pega todos os pods que dentro do match labels é goserver #veja arquivo deployment
  type: NodePort
  ports: 
  - name: goserver-service
    port: 80 # Esta é a porta que o serviço expõe dentro do cluster Kubernetes. Qualquer pod que se conectar a este serviço usará a porta 80.
    nodePort: 30001 #Esta é a porta exposta em cada nó do cluster Kubernetes 
    targetPort: 8000 #Porta do container
    protocol: TCP

    #Gera uma porta e libera em todos os nodes do cluster

#Rodar : 
# kubectl apply -f k8s/service2.yaml
# kubectl get services

# Como acessar ?
# Redirecionamento de porta : 
# kubectl port-forward service/goserver-service 8000:80 

#Porta 80: A porta onde o serviço Kubernetes escuta dentro do cluster.
#Porta 8000: A porta no container do pod para onde o serviço redireciona o tráfego.
#Porta 30001: A porta exposta nos nós do cluster para acesso externo ao serviço.

# Qualquer um q acessar qualquer um dos nodes pela porta 30001 vai cair na porta 80 do serviço e será direcionado
# para a porta 8000 do container que está rodando esse serviço